{
 "title": "Ambient Weather",
 "description": "A dashboard for ambient weather collector",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "mac", "label": "MacAddress", "query": { "query": "label_values(aw_mac)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "location", "label": "Location", "query": { "query": "label_values(aw_location)" } },
   { "name": "name", "label": "Name", "query": { "query": "label_values(aw_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aw_tempin{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily Rainfall",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aw_dailyrainin{aw_mac=\"$mac\", aw_location=\"$location\", aw_name=\"$name\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Windspeed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(aw_windspeedmph{aw_mac=\"$mac\", aw_location=\"$location\", aw_name=\"$name\", instance=\"$instance\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dewpoint",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(mac) (aw_dewpoint{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temp(Feels Like)",
     "type": "timeseries",
     "description": "Feels like temp",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
     "targets": [
      {
       "expr": "aw_feelslike{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg_over_time(aw_humidity{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[24h])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Dewpoint",
     "type": "timeseries",
     "description": "The average dew point over time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
     "targets": [
      {
       "expr": "avg_over_time(aw_dewpoint{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[1h])"
      },
      {
       "expr": "aw_dewpoint{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Daily Current Temp",
     "type": "timeseries",
     "description": "The current temperature over time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
     "targets": [
      {
       "expr": "aw_tempin{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg_over_time(aw_tempin{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[1h])",
       "legendFormat": "{{Average Temperature}}"
      }
     ]
    },
    {
     "title": "Average Dewpoint and Temp",
     "type": "timeseries",
     "description": "The average dew point over time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
     "targets": [
      {
       "expr": "avg_over_time(aw_dewpoint{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[1h])"
      },
      {
       "expr": "aw_tempin{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Rain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily Rainfall",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "lengthin" } },
     "targets": [
      {
       "expr": "avg_over_time(aw_dailyrainin{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[60m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "aw_dailyrainin{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Weekly Rainfall",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "lengthin" } },
     "targets": [
      {
       "expr": "avg_over_time(aw_weeklyrainin{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[24h])",
       "legendFormat": "__auto"
      },
      {
       "expr": "aw_weeklyrainin{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Monthly Rainfall",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "lengthin" } },
     "targets": [
      {
       "expr": "avg_over_time(aw_monthlyrainin{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[7d])",
       "legendFormat": "__auto"
      },
      {
       "expr": "aw_monthlyrainin{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Yearly Rainfall",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "lengthin" } },
     "targets": [
      {
       "expr": "avg_over_time(aw_yearlyrainin{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[30d])",
       "legendFormat": "__auto"
      },
      {
       "expr": "aw_yearlyrainin{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Humidity",
     "type": "timeseries",
     "description": "The current humidity.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "expr": "aw_humidity{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "delta(aw_humidity{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[1h])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Humidity",
     "type": "timeseries",
     "description": "The average humidity with the rate of change.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "expr": "avg_over_time(aw_humidity{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[24h])",
       "legendFormat": "__auto"
      },
      {
       "expr": "aw_humidity{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Wind", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Wind Gust past hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(aw_windspeedmph{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Gust",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aw_maxgust{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Direction in degrees",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aw_winddir{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Windspeed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "expr": "aw_windspeedmph{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(aw_windspeedmph{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lightning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lightning Strikes per day",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "aw_lightningday{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg_over_time(aw_lightningday{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[24h])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Strike Distance",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aw_lightningdistance{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "aw_lightninghour{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Lightning Strikes per hour",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "aw_lightninghour{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg_over_time(aw_lightninghour{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[1h])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Solar Radiation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Solar Radiation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "aw_solarradiation{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg. Solar Radiation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "avg_over_time(aw_solarradiation{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[1h])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Barometric Pressure",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "pressurehg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aw_barametric{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Barometric Pressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "pressurehg" } },
     "targets": [
      {
       "expr": "aw_barametric{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg_over_time(aw_barametric{aw_mac=\"$mac\", instance=\"$instance\", aw_location=\"$location\", aw_name=\"$name\"}[1h])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}